### ISSUE TITLE
Twitter share no link

### ISSUE THREAD

**Issue by wenyaoliu** [Lhcfl/hexo-theme-anatolo#1]
Thank you for this powerful and beautiful theme. I created my own blog [here](https://wenyaoliu.github.io/blog/). 

However, several issues were found and may be improved:

1. "热度" after the visitors' count is not familiar to English users. (Solved by replacing that in a. rug file).
2.  Twitter sharing is just jumping to the website with no sharing link.  **To be solved.** 
3. Could you provide more details on how to set the tags, archives, etc?

Thank you.

**Comment by Lhcfl** [comment]
Fixed Twitter sharing
