### ISSUE TITLE
RSS 按钮工作不正常

### ISSUE THREAD

**Issue by MyBlueHorizon** [Lhcfl/hexo-theme-anatolo#12]
点击 RSS 按钮后未跳转到 RSS 页面，在浏览器中弹出消息提示
> {}

但浏览器确实成功请求了 RSS 文件

**Comment by Lhcfl** [comment]
感谢提醒，准备进行修复

**Comment by Lhcfl** [comment]
Fixed in https://github.com/Lhcfl/hexo-theme-anatolo/commit/6287a2892b4cc0bbc17c596a43bf387587846032
