### ISSUE TITLE
这是关于hexo-Anatole的询问

### ISSUE THREAD

**Issue by Dimp07** [Lhcfl/hexo-theme-anatolo#16]
博主你好，我在使用你的Anatole主题时发现页面无法正常显示表格
页面显示如下：

![PixPin_2024-01-05_19-47-58](https://github.com/Lhcfl/hexo-theme-anatolo/assets/129408828/441e635a-52c8-4ef4-9a11-117c6b0ee3e3)

markdow内容如下：
![PixPin_2024-01-05_19-48-15](https://github.com/Lhcfl/hexo-theme-anatolo/assets/129408828/a26ddda0-4df2-4576-b0ab-f269bb63bb13)

请问该如何解决？期待你的解答，谢谢！

**Comment by Lhcfl** [comment]
fixed
