### ISSUE TITLE
这是关于LaTex数学公式在页面中无法正常显示的询问

### ISSUE THREAD

**Issue by Dimp07** [Lhcfl/hexo-theme-anatolo#18]
页面显示如下：
![image](https://github.com/Lhcfl/hexo-theme-anatolo/assets/129408828/9761e37d-5d38-4d49-b47a-6680687c4389)
在markdown中显示如下：
![image](https://github.com/Lhcfl/hexo-theme-anatolo/assets/129408828/b95fdc08-785c-4e04-bd2a-aaa8a947c4cb)
麻烦博主了

**Comment by Lhcfl** [comment]
参考 https://lhcfl.github.io/2023/10/13/Anatolo%20Math%20Support/

在Hexo的设计里这不是主题负责的，你需要自己安装数学插件

**Comment by Dimp07** [comment]
好的多谢了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月6日(星期六) 中午11:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Lhcfl/hexo-theme-anatolo] 这是关于LaTex数学公式在页面中无法正常显示的询问 (Issue #18)





 
参考 https://lhcfl.github.io/2023/10/13/Anatolo%20Math%20Support/
 
在Hexo的设计里这不是主题负责的，你需要自己安装数学插件
