### ISSUE TITLE
这是关于页面布局有略微差别的询问

### ISSUE THREAD

**Issue by Dimp07** [Lhcfl/hexo-theme-anatolo#19]
在页面中，”首页“与”标签“的页面布局是一致的，但是”归档“的页面布局有略微差别
![PixPin_2024-01-05_21-01-56](https://github.com/Lhcfl/hexo-theme-anatolo/assets/129408828/c44496c5-6748-4809-9ba9-f6daae5dd561)
麻烦博主了

**Comment by Lhcfl** [comment]
无法在 https://lhcfl.github.io/ 复现，我觉得是你的问题？

**Comment by Southseast** [comment]
> 无法在 https://lhcfl.github.io/ 复现，我觉得是你的问题？

其实你的“关于”和“首页”也有这样的问题？

来自 Google Chrome Version 122.0.6261.129 (Official Build) (arm64)。

**Comment by Lhcfl** [comment]
发现原因了，这是因为右边的滑动条在你内容不多的时候消失了，导致屏幕变宽了一点点
