### ISSUE TITLE
能否关闭browser-sync

### ISSUE THREAD

**Issue by reeowo** [Lhcfl/hexo-theme-anatolo#4]

**Comment by Lhcfl** [comment]
这是什么

**Comment by reeowo** [comment]
![image](https://user-images.githubusercontent.com/72610346/195804931-1ef33ac4-4548-4125-b894-95ad7ef54048.png)
您好，设置主题后，hexo s启动会提示browser-sync启动了，IP:3000能访问到这个插件，在哪里能关闭呢

**Comment by Lhcfl** [comment]
![image](https://user-images.githubusercontent.com/41134017/195805724-13718da2-d4c4-41e0-a290-742ccb42d19a.png)
事实上我觉得，你应该检查一下你本地安装了些什么。本主题并没有使用browser-sync。

**Comment by reeowo** [comment]
> ![image](https://user-images.githubusercontent.com/41134017/195805724-13718da2-d4c4-41e0-a290-742ccb42d19a.png) 事实上我觉得，你应该检查一下你本地安装了些什么。本主题并没有使用browser-sync。

好的！我明白了，非常感谢！
