### ISSUE TITLE
站点位于子目录时路径错误

### ISSUE THREAD

**Issue by MyBlueHorizon** [Lhcfl/hexo-theme-anatolo#6]
在站点和主题的_config.yml中已经配置了url和root，但对于archive和tag(可能还有其它)并不生效。
或许修改archive和tag的指向路径会有用，但不确定会不会引起潜在的bug。
Update：
logo2x地址跟随主配置正常改变，但logo和favicon地址未改变
Update：
rss地址跟随主配置正常改变

**Comment by Lhcfl** [comment]
啊，你说得对，确实有这个问题，因为链接是用a(href=xxx)的形式生成的。
我可能要翻一下文档才能解决这个问题……因为这个主题是fork的ben02的Anatole，我还没研究hexo提供的链接生成方式

**Comment by Lhcfl** [comment]
虽然不知道你还记不记得这个，但是我现在把他修复了

**Comment by MyBlueHorizon** [comment]
> 虽然不知道你还记不记得这个，但是我现在把他修复了

好耶，感谢您的帮助
