### ISSUE TITLE
关于gitalk的问题

### ISSUE THREAD

**Issue by emt0re0** [Lhcfl/hexo-theme-anatolo#8]
搭建博客时，遇到了下面两个问题：
1.使用Github账户登陆评论区时会返回首页或者404报错
2.未找到相关的Issues进行评论，请联系XXX进行创建
希望您能回答一下，感激不尽！！！

**Comment by Lhcfl** [comment]
如果我没猜错，应该是你的gitalk配置错了吧？我自己的blog可以正常使用gitalk。

**Comment by emt0re0** [comment]
配置应该是没问题的，我检查过了

**Comment by emt0re0** [comment]
还可能有其他方面的问题吗
